// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deduction.proto

#include "deduction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_deduction_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DeductionStruct_deduction_2eproto;
namespace protocol {
namespace payment {
namespace deduction {
namespace v1 {
class DeductionStructDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DeductionStruct> _instance;
} _DeductionStruct_default_instance_;
class DeductionAdminRespDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DeductionAdminResp> _instance;
} _DeductionAdminResp_default_instance_;
class DeductionAdminReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DeductionAdminReq> _instance;
} _DeductionAdminReq_default_instance_;
}  // namespace v1
}  // namespace deduction
}  // namespace payment
}  // namespace protocol
static void InitDefaultsscc_info_DeductionAdminReq_deduction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::payment::deduction::v1::_DeductionAdminReq_default_instance_;
    new (ptr) ::protocol::payment::deduction::v1::DeductionAdminReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::payment::deduction::v1::DeductionAdminReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DeductionAdminReq_deduction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DeductionAdminReq_deduction_2eproto}, {}};

static void InitDefaultsscc_info_DeductionAdminResp_deduction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::payment::deduction::v1::_DeductionAdminResp_default_instance_;
    new (ptr) ::protocol::payment::deduction::v1::DeductionAdminResp();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::payment::deduction::v1::DeductionAdminResp::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DeductionAdminResp_deduction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_DeductionAdminResp_deduction_2eproto}, {
      &scc_info_DeductionStruct_deduction_2eproto.base,}};

static void InitDefaultsscc_info_DeductionStruct_deduction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::payment::deduction::v1::_DeductionStruct_default_instance_;
    new (ptr) ::protocol::payment::deduction::v1::DeductionStruct();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::payment::deduction::v1::DeductionStruct::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DeductionStruct_deduction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DeductionStruct_deduction_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_deduction_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_deduction_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_deduction_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_deduction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionStruct, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionStruct, title_),
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionStruct, desc_),
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionStruct, status_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionAdminResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionAdminResp, header_),
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionAdminResp, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionAdminReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::protocol::payment::deduction::v1::DeductionAdminReq, header_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protocol::payment::deduction::v1::DeductionStruct)},
  { 8, -1, sizeof(::protocol::payment::deduction::v1::DeductionAdminResp)},
  { 15, -1, sizeof(::protocol::payment::deduction::v1::DeductionAdminReq)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protocol::payment::deduction::v1::_DeductionStruct_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protocol::payment::deduction::v1::_DeductionAdminResp_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protocol::payment::deduction::v1::_DeductionAdminReq_default_instance_),
};

const char descriptor_table_protodef_deduction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017deduction.proto\022\035protocol.payment.dedu"
  "ction.v1\">\n\017DeductionStruct\022\r\n\005title\030\001 \001"
  "(\t\022\014\n\004desc\030\002 \001(\t\022\016\n\006status\030\003 \001(\r\"b\n\022Dedu"
  "ctionAdminResp\022\016\n\006header\030\001 \001(\t\022<\n\004data\030\002"
  " \003(\0132..protocol.payment.deduction.v1.Ded"
  "uctionStruct\"#\n\021DeductionAdminReq\022\016\n\006hea"
  "der\030\001 \001(\t2\200\002\n\021DeductionAdminApi\022y\n\020GetDe"
  "ductionList\0220.protocol.payment.deduction"
  ".v1.DeductionAdminReq\0321.protocol.payment"
  ".deduction.v1.DeductionAdminResp\"\000\022p\n\007Ad"
  "minOp\0220.protocol.payment.deduction.v1.De"
  "ductionAdminReq\0321.protocol.payment.deduc"
  "tion.v1.DeductionAdminResp\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_deduction_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_deduction_2eproto_sccs[3] = {
  &scc_info_DeductionAdminReq_deduction_2eproto.base,
  &scc_info_DeductionAdminResp_deduction_2eproto.base,
  &scc_info_DeductionStruct_deduction_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_deduction_2eproto_once;
static bool descriptor_table_deduction_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_deduction_2eproto = {
  &descriptor_table_deduction_2eproto_initialized, descriptor_table_protodef_deduction_2eproto, "deduction.proto", 516,
  &descriptor_table_deduction_2eproto_once, descriptor_table_deduction_2eproto_sccs, descriptor_table_deduction_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_deduction_2eproto::offsets,
  file_level_metadata_deduction_2eproto, 3, file_level_enum_descriptors_deduction_2eproto, file_level_service_descriptors_deduction_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_deduction_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_deduction_2eproto), true);
namespace protocol {
namespace payment {
namespace deduction {
namespace v1 {

// ===================================================================

void DeductionStruct::InitAsDefaultInstance() {
}
class DeductionStruct::_Internal {
 public:
};

DeductionStruct::DeductionStruct()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.payment.deduction.v1.DeductionStruct)
}
DeductionStruct::DeductionStruct(const DeductionStruct& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  title_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_title().empty()) {
    title_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.title_);
  }
  desc_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_desc().empty()) {
    desc_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.desc_);
  }
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:protocol.payment.deduction.v1.DeductionStruct)
}

void DeductionStruct::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DeductionStruct_deduction_2eproto.base);
  title_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  desc_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  status_ = 0u;
}

DeductionStruct::~DeductionStruct() {
  // @@protoc_insertion_point(destructor:protocol.payment.deduction.v1.DeductionStruct)
  SharedDtor();
}

void DeductionStruct::SharedDtor() {
  title_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  desc_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DeductionStruct::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DeductionStruct& DeductionStruct::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DeductionStruct_deduction_2eproto.base);
  return *internal_default_instance();
}


void DeductionStruct::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.payment.deduction.v1.DeductionStruct)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  title_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  desc_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  status_ = 0u;
  _internal_metadata_.Clear();
}

const char* DeductionStruct::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string title = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_title();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protocol.payment.deduction.v1.DeductionStruct.title"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string desc = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_desc();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protocol.payment.deduction.v1.DeductionStruct.desc"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DeductionStruct::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.payment.deduction.v1.DeductionStruct)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string title = 1;
  if (this->title().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_title().data(), static_cast<int>(this->_internal_title().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.payment.deduction.v1.DeductionStruct.title");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_title(), target);
  }

  // string desc = 2;
  if (this->desc().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_desc().data(), static_cast<int>(this->_internal_desc().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.payment.deduction.v1.DeductionStruct.desc");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_desc(), target);
  }

  // uint32 status = 3;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.payment.deduction.v1.DeductionStruct)
  return target;
}

size_t DeductionStruct::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.payment.deduction.v1.DeductionStruct)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string title = 1;
  if (this->title().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_title());
  }

  // string desc = 2;
  if (this->desc().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_desc());
  }

  // uint32 status = 3;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeductionStruct::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.payment.deduction.v1.DeductionStruct)
  GOOGLE_DCHECK_NE(&from, this);
  const DeductionStruct* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DeductionStruct>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.payment.deduction.v1.DeductionStruct)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.payment.deduction.v1.DeductionStruct)
    MergeFrom(*source);
  }
}

void DeductionStruct::MergeFrom(const DeductionStruct& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.payment.deduction.v1.DeductionStruct)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.title().size() > 0) {

    title_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.title_);
  }
  if (from.desc().size() > 0) {

    desc_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.desc_);
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void DeductionStruct::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.payment.deduction.v1.DeductionStruct)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeductionStruct::CopyFrom(const DeductionStruct& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.payment.deduction.v1.DeductionStruct)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeductionStruct::IsInitialized() const {
  return true;
}

void DeductionStruct::InternalSwap(DeductionStruct* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  title_.Swap(&other->title_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  desc_.Swap(&other->desc_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(status_, other->status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DeductionStruct::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void DeductionAdminResp::InitAsDefaultInstance() {
}
class DeductionAdminResp::_Internal {
 public:
};

DeductionAdminResp::DeductionAdminResp()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.payment.deduction.v1.DeductionAdminResp)
}
DeductionAdminResp::DeductionAdminResp(const DeductionAdminResp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  header_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_header().empty()) {
    header_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.header_);
  }
  // @@protoc_insertion_point(copy_constructor:protocol.payment.deduction.v1.DeductionAdminResp)
}

void DeductionAdminResp::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DeductionAdminResp_deduction_2eproto.base);
  header_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

DeductionAdminResp::~DeductionAdminResp() {
  // @@protoc_insertion_point(destructor:protocol.payment.deduction.v1.DeductionAdminResp)
  SharedDtor();
}

void DeductionAdminResp::SharedDtor() {
  header_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DeductionAdminResp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DeductionAdminResp& DeductionAdminResp::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DeductionAdminResp_deduction_2eproto.base);
  return *internal_default_instance();
}


void DeductionAdminResp::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.payment.deduction.v1.DeductionAdminResp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  header_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* DeductionAdminResp::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_header();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protocol.payment.deduction.v1.DeductionAdminResp.header"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .protocol.payment.deduction.v1.DeductionStruct data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DeductionAdminResp::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.payment.deduction.v1.DeductionAdminResp)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string header = 1;
  if (this->header().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_header().data(), static_cast<int>(this->_internal_header().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.payment.deduction.v1.DeductionAdminResp.header");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_header(), target);
  }

  // repeated .protocol.payment.deduction.v1.DeductionStruct data = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.payment.deduction.v1.DeductionAdminResp)
  return target;
}

size_t DeductionAdminResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.payment.deduction.v1.DeductionAdminResp)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protocol.payment.deduction.v1.DeductionStruct data = 2;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string header = 1;
  if (this->header().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_header());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeductionAdminResp::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.payment.deduction.v1.DeductionAdminResp)
  GOOGLE_DCHECK_NE(&from, this);
  const DeductionAdminResp* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DeductionAdminResp>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.payment.deduction.v1.DeductionAdminResp)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.payment.deduction.v1.DeductionAdminResp)
    MergeFrom(*source);
  }
}

void DeductionAdminResp::MergeFrom(const DeductionAdminResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.payment.deduction.v1.DeductionAdminResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from.header().size() > 0) {

    header_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.header_);
  }
}

void DeductionAdminResp::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.payment.deduction.v1.DeductionAdminResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeductionAdminResp::CopyFrom(const DeductionAdminResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.payment.deduction.v1.DeductionAdminResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeductionAdminResp::IsInitialized() const {
  return true;
}

void DeductionAdminResp::InternalSwap(DeductionAdminResp* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  header_.Swap(&other->header_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata DeductionAdminResp::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void DeductionAdminReq::InitAsDefaultInstance() {
}
class DeductionAdminReq::_Internal {
 public:
};

DeductionAdminReq::DeductionAdminReq()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.payment.deduction.v1.DeductionAdminReq)
}
DeductionAdminReq::DeductionAdminReq(const DeductionAdminReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  header_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_header().empty()) {
    header_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.header_);
  }
  // @@protoc_insertion_point(copy_constructor:protocol.payment.deduction.v1.DeductionAdminReq)
}

void DeductionAdminReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DeductionAdminReq_deduction_2eproto.base);
  header_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

DeductionAdminReq::~DeductionAdminReq() {
  // @@protoc_insertion_point(destructor:protocol.payment.deduction.v1.DeductionAdminReq)
  SharedDtor();
}

void DeductionAdminReq::SharedDtor() {
  header_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DeductionAdminReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DeductionAdminReq& DeductionAdminReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DeductionAdminReq_deduction_2eproto.base);
  return *internal_default_instance();
}


void DeductionAdminReq::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.payment.deduction.v1.DeductionAdminReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  header_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* DeductionAdminReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_header();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "protocol.payment.deduction.v1.DeductionAdminReq.header"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DeductionAdminReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.payment.deduction.v1.DeductionAdminReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string header = 1;
  if (this->header().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_header().data(), static_cast<int>(this->_internal_header().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protocol.payment.deduction.v1.DeductionAdminReq.header");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_header(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.payment.deduction.v1.DeductionAdminReq)
  return target;
}

size_t DeductionAdminReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.payment.deduction.v1.DeductionAdminReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string header = 1;
  if (this->header().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_header());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DeductionAdminReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.payment.deduction.v1.DeductionAdminReq)
  GOOGLE_DCHECK_NE(&from, this);
  const DeductionAdminReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DeductionAdminReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.payment.deduction.v1.DeductionAdminReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.payment.deduction.v1.DeductionAdminReq)
    MergeFrom(*source);
  }
}

void DeductionAdminReq::MergeFrom(const DeductionAdminReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.payment.deduction.v1.DeductionAdminReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.header().size() > 0) {

    header_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.header_);
  }
}

void DeductionAdminReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.payment.deduction.v1.DeductionAdminReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeductionAdminReq::CopyFrom(const DeductionAdminReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.payment.deduction.v1.DeductionAdminReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeductionAdminReq::IsInitialized() const {
  return true;
}

void DeductionAdminReq::InternalSwap(DeductionAdminReq* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  header_.Swap(&other->header_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata DeductionAdminReq::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace deduction
}  // namespace payment
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protocol::payment::deduction::v1::DeductionStruct* Arena::CreateMaybeMessage< ::protocol::payment::deduction::v1::DeductionStruct >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::payment::deduction::v1::DeductionStruct >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::payment::deduction::v1::DeductionAdminResp* Arena::CreateMaybeMessage< ::protocol::payment::deduction::v1::DeductionAdminResp >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::payment::deduction::v1::DeductionAdminResp >(arena);
}
template<> PROTOBUF_NOINLINE ::protocol::payment::deduction::v1::DeductionAdminReq* Arena::CreateMaybeMessage< ::protocol::payment::deduction::v1::DeductionAdminReq >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::payment::deduction::v1::DeductionAdminReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
