// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: deduction.proto

#include "deduction.pb.h"
#include "deduction.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace protocol {
namespace payment {
namespace deduction {
namespace v1 {

static const char* DeductionAdminApi_method_names[] = {
  "/protocol.payment.deduction.v1.DeductionAdminApi/GetDeductionList",
  "/protocol.payment.deduction.v1.DeductionAdminApi/GetExpiredDeductionList",
  "/protocol.payment.deduction.v1.DeductionAdminApi/OpenDeduction",
  "/protocol.payment.deduction.v1.DeductionAdminApi/CloseDeduction",
  "/protocol.payment.deduction.v1.DeductionAdminApi/CreateDeduction",
};

std::unique_ptr< DeductionAdminApi::Stub> DeductionAdminApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeductionAdminApi::Stub> stub(new DeductionAdminApi::Stub(channel));
  return stub;
}

DeductionAdminApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetDeductionList_(DeductionAdminApi_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetExpiredDeductionList_(DeductionAdminApi_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenDeduction_(DeductionAdminApi_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CloseDeduction_(DeductionAdminApi_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateDeduction_(DeductionAdminApi_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DeductionAdminApi::Stub::GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetDeductionList_, context, request, response);
}

void DeductionAdminApi::Stub::experimental_async::GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetDeductionList_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetDeductionList_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetDeductionList_, context, request, response, reactor);
}

void DeductionAdminApi::Stub::experimental_async::GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetDeductionList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::AsyncGetDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_GetDeductionList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::PrepareAsyncGetDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_GetDeductionList_, context, request, false);
}

::grpc::Status DeductionAdminApi::Stub::GetExpiredDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetExpiredDeductionList_, context, request, response);
}

void DeductionAdminApi::Stub::experimental_async::GetExpiredDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetExpiredDeductionList_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::GetExpiredDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetExpiredDeductionList_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::GetExpiredDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetExpiredDeductionList_, context, request, response, reactor);
}

void DeductionAdminApi::Stub::experimental_async::GetExpiredDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetExpiredDeductionList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::AsyncGetExpiredDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_GetExpiredDeductionList_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::PrepareAsyncGetExpiredDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_GetExpiredDeductionList_, context, request, false);
}

::grpc::Status DeductionAdminApi::Stub::OpenDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_OpenDeduction_, context, request, response);
}

void DeductionAdminApi::Stub::experimental_async::OpenDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_OpenDeduction_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::OpenDeduction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_OpenDeduction_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::OpenDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_OpenDeduction_, context, request, response, reactor);
}

void DeductionAdminApi::Stub::experimental_async::OpenDeduction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_OpenDeduction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::AsyncOpenDeductionRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_OpenDeduction_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::PrepareAsyncOpenDeductionRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_OpenDeduction_, context, request, false);
}

::grpc::Status DeductionAdminApi::Stub::CloseDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CloseDeduction_, context, request, response);
}

void DeductionAdminApi::Stub::experimental_async::CloseDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CloseDeduction_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::CloseDeduction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CloseDeduction_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::CloseDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CloseDeduction_, context, request, response, reactor);
}

void DeductionAdminApi::Stub::experimental_async::CloseDeduction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CloseDeduction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::AsyncCloseDeductionRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_CloseDeduction_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::PrepareAsyncCloseDeductionRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_CloseDeduction_, context, request, false);
}

::grpc::Status DeductionAdminApi::Stub::CreateDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateDeduction_, context, request, response);
}

void DeductionAdminApi::Stub::experimental_async::CreateDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateDeduction_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::CreateDeduction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateDeduction_, context, request, response, std::move(f));
}

void DeductionAdminApi::Stub::experimental_async::CreateDeduction(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateDeduction_, context, request, response, reactor);
}

void DeductionAdminApi::Stub::experimental_async::CreateDeduction(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CreateDeduction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::AsyncCreateDeductionRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_CreateDeduction_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionResp>* DeductionAdminApi::Stub::PrepareAsyncCreateDeductionRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::payment::deduction::v1::DeductionResp>::Create(channel_.get(), cq, rpcmethod_CreateDeduction_, context, request, false);
}

DeductionAdminApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeductionAdminApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeductionAdminApi::Service, ::protocol::payment::deduction::v1::DeductionReq, ::protocol::payment::deduction::v1::DeductionResp>(
          [](DeductionAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::payment::deduction::v1::DeductionReq* req,
             ::protocol::payment::deduction::v1::DeductionResp* resp) {
               return service->GetDeductionList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeductionAdminApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeductionAdminApi::Service, ::protocol::payment::deduction::v1::DeductionReq, ::protocol::payment::deduction::v1::DeductionResp>(
          [](DeductionAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::payment::deduction::v1::DeductionReq* req,
             ::protocol::payment::deduction::v1::DeductionResp* resp) {
               return service->GetExpiredDeductionList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeductionAdminApi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeductionAdminApi::Service, ::protocol::payment::deduction::v1::DeductionReq, ::protocol::payment::deduction::v1::DeductionResp>(
          [](DeductionAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::payment::deduction::v1::DeductionReq* req,
             ::protocol::payment::deduction::v1::DeductionResp* resp) {
               return service->OpenDeduction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeductionAdminApi_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeductionAdminApi::Service, ::protocol::payment::deduction::v1::DeductionReq, ::protocol::payment::deduction::v1::DeductionResp>(
          [](DeductionAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::payment::deduction::v1::DeductionReq* req,
             ::protocol::payment::deduction::v1::DeductionResp* resp) {
               return service->CloseDeduction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeductionAdminApi_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeductionAdminApi::Service, ::protocol::payment::deduction::v1::DeductionReq, ::protocol::payment::deduction::v1::DeductionResp>(
          [](DeductionAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::payment::deduction::v1::DeductionReq* req,
             ::protocol::payment::deduction::v1::DeductionResp* resp) {
               return service->CreateDeduction(ctx, req, resp);
             }, this)));
}

DeductionAdminApi::Service::~Service() {
}

::grpc::Status DeductionAdminApi::Service::GetDeductionList(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeductionAdminApi::Service::GetExpiredDeductionList(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeductionAdminApi::Service::OpenDeduction(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeductionAdminApi::Service::CloseDeduction(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeductionAdminApi::Service::CreateDeduction(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionReq* request, ::protocol::payment::deduction::v1::DeductionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protocol
}  // namespace payment
}  // namespace deduction
}  // namespace v1

