// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: deduction.proto
#ifndef GRPC_deduction_2eproto__INCLUDED
#define GRPC_deduction_2eproto__INCLUDED

#include "deduction.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace protocol {
namespace payment {
namespace deduction {
namespace v1 {

// The greeting service definition.
class DeductionAdminApi final {
 public:
  static constexpr char const* service_full_name() {
    return "protocol.payment.deduction.v1.DeductionAdminApi";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::protocol::payment::deduction::v1::DeductionAdminResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>> AsyncGetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>>(AsyncGetDeductionListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>> PrepareAsyncGetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>>(PrepareAsyncGetDeductionListRaw(context, request, cq));
    }
    virtual ::grpc::Status AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::protocol::payment::deduction::v1::DeductionAdminResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>> AsyncAdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>>(AsyncAdminOpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>> PrepareAsyncAdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>>(PrepareAsyncAdminOpRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>* AsyncGetDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>* PrepareAsyncGetDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>* AsyncAdminOpRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protocol::payment::deduction::v1::DeductionAdminResp>* PrepareAsyncAdminOpRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::protocol::payment::deduction::v1::DeductionAdminResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>> AsyncGetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>>(AsyncGetDeductionListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>> PrepareAsyncGetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>>(PrepareAsyncGetDeductionListRaw(context, request, cq));
    }
    ::grpc::Status AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::protocol::payment::deduction::v1::DeductionAdminResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>> AsyncAdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>>(AsyncAdminOpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>> PrepareAsyncAdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>>(PrepareAsyncAdminOpRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) override;
      void GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetDeductionList(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetDeductionList(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) override;
      void AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void AdminOp(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>* AsyncGetDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>* PrepareAsyncGetDeductionListRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>* AsyncAdminOpRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protocol::payment::deduction::v1::DeductionAdminResp>* PrepareAsyncAdminOpRaw(::grpc::ClientContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetDeductionList_;
    const ::grpc::internal::RpcMethod rpcmethod_AdminOp_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetDeductionList(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response);
    virtual ::grpc::Status AdminOp(::grpc::ServerContext* context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDeductionList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDeductionList() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetDeductionList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDeductionList(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDeductionList(::grpc::ServerContext* context, ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::grpc::ServerAsyncResponseWriter< ::protocol::payment::deduction::v1::DeductionAdminResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AdminOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AdminOp() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AdminOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AdminOp(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdminOp(::grpc::ServerContext* context, ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::grpc::ServerAsyncResponseWriter< ::protocol::payment::deduction::v1::DeductionAdminResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetDeductionList<WithAsyncMethod_AdminOp<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetDeductionList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetDeductionList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response) { return this->GetDeductionList(context, request, response); }));}
    void SetMessageAllocatorFor_GetDeductionList(
        ::grpc::experimental::MessageAllocator< ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetDeductionList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDeductionList(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetDeductionList(
      ::grpc::CallbackServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetDeductionList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AdminOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_AdminOp() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::protocol::payment::deduction::v1::DeductionAdminReq* request, ::protocol::payment::deduction::v1::DeductionAdminResp* response) { return this->AdminOp(context, request, response); }));}
    void SetMessageAllocatorFor_AdminOp(
        ::grpc::experimental::MessageAllocator< ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_AdminOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AdminOp(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* AdminOp(
      ::grpc::CallbackServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* AdminOp(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetDeductionList<ExperimentalWithCallbackMethod_AdminOp<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetDeductionList<ExperimentalWithCallbackMethod_AdminOp<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetDeductionList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDeductionList() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetDeductionList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDeductionList(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AdminOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AdminOp() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AdminOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AdminOp(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDeductionList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDeductionList() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetDeductionList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDeductionList(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDeductionList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AdminOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AdminOp() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AdminOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AdminOp(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdminOp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetDeductionList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetDeductionList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDeductionList(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetDeductionList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDeductionList(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetDeductionList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetDeductionList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AdminOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_AdminOp() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AdminOp(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_AdminOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AdminOp(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* AdminOp(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* AdminOp(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDeductionList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDeductionList() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>* streamer) {
                       return this->StreamedGetDeductionList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDeductionList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDeductionList(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDeductionList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protocol::payment::deduction::v1::DeductionAdminReq,::protocol::payment::deduction::v1::DeductionAdminResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AdminOp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AdminOp() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::protocol::payment::deduction::v1::DeductionAdminReq, ::protocol::payment::deduction::v1::DeductionAdminResp>* streamer) {
                       return this->StreamedAdminOp(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AdminOp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AdminOp(::grpc::ServerContext* /*context*/, const ::protocol::payment::deduction::v1::DeductionAdminReq* /*request*/, ::protocol::payment::deduction::v1::DeductionAdminResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdminOp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protocol::payment::deduction::v1::DeductionAdminReq,::protocol::payment::deduction::v1::DeductionAdminResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetDeductionList<WithStreamedUnaryMethod_AdminOp<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetDeductionList<WithStreamedUnaryMethod_AdminOp<Service > > StreamedService;
};

}  // namespace v1
}  // namespace deduction
}  // namespace payment
}  // namespace protocol


#endif  // GRPC_deduction_2eproto__INCLUDED
