// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deduction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_deduction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_deduction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_deduction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_deduction_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_deduction_2eproto;
namespace protocol {
namespace payment {
namespace deduction {
namespace v1 {
class DeductionReq;
class DeductionReqDefaultTypeInternal;
extern DeductionReqDefaultTypeInternal _DeductionReq_default_instance_;
class DeductionResp;
class DeductionRespDefaultTypeInternal;
extern DeductionRespDefaultTypeInternal _DeductionResp_default_instance_;
class DeductionStruct;
class DeductionStructDefaultTypeInternal;
extern DeductionStructDefaultTypeInternal _DeductionStruct_default_instance_;
}  // namespace v1
}  // namespace deduction
}  // namespace payment
}  // namespace protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::protocol::payment::deduction::v1::DeductionReq* Arena::CreateMaybeMessage<::protocol::payment::deduction::v1::DeductionReq>(Arena*);
template<> ::protocol::payment::deduction::v1::DeductionResp* Arena::CreateMaybeMessage<::protocol::payment::deduction::v1::DeductionResp>(Arena*);
template<> ::protocol::payment::deduction::v1::DeductionStruct* Arena::CreateMaybeMessage<::protocol::payment::deduction::v1::DeductionStruct>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protocol {
namespace payment {
namespace deduction {
namespace v1 {

// ===================================================================

class DeductionStruct :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.payment.deduction.v1.DeductionStruct) */ {
 public:
  DeductionStruct();
  virtual ~DeductionStruct();

  DeductionStruct(const DeductionStruct& from);
  DeductionStruct(DeductionStruct&& from) noexcept
    : DeductionStruct() {
    *this = ::std::move(from);
  }

  inline DeductionStruct& operator=(const DeductionStruct& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeductionStruct& operator=(DeductionStruct&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DeductionStruct& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeductionStruct* internal_default_instance() {
    return reinterpret_cast<const DeductionStruct*>(
               &_DeductionStruct_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DeductionStruct& a, DeductionStruct& b) {
    a.Swap(&b);
  }
  inline void Swap(DeductionStruct* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeductionStruct* New() const final {
    return CreateMaybeMessage<DeductionStruct>(nullptr);
  }

  DeductionStruct* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeductionStruct>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DeductionStruct& from);
  void MergeFrom(const DeductionStruct& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeductionStruct* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.payment.deduction.v1.DeductionStruct";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_deduction_2eproto);
    return ::descriptor_table_deduction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 1,
    kDescFieldNumber = 2,
    kStatusFieldNumber = 3,
    kIdFieldNumber = 4,
    kPayMethodIdFieldNumber = 5,
  };
  // string title = 1;
  void clear_title();
  const std::string& title() const;
  void set_title(const std::string& value);
  void set_title(std::string&& value);
  void set_title(const char* value);
  void set_title(const char* value, size_t size);
  std::string* mutable_title();
  std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string desc = 2;
  void clear_desc();
  const std::string& desc() const;
  void set_desc(const std::string& value);
  void set_desc(std::string&& value);
  void set_desc(const char* value);
  void set_desc(const char* value, size_t size);
  std::string* mutable_desc();
  std::string* release_desc();
  void set_allocated_desc(std::string* desc);
  private:
  const std::string& _internal_desc() const;
  void _internal_set_desc(const std::string& value);
  std::string* _internal_mutable_desc();
  public:

  // uint32 status = 3;
  void clear_status();
  ::PROTOBUF_NAMESPACE_ID::uint32 status() const;
  void set_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_status() const;
  void _internal_set_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 id = 4;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 pay_method_id = 5;
  void clear_pay_method_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 pay_method_id() const;
  void set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_pay_method_id() const;
  void _internal_set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.payment.deduction.v1.DeductionStruct)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr desc_;
  ::PROTOBUF_NAMESPACE_ID::uint32 status_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 pay_method_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_deduction_2eproto;
};
// -------------------------------------------------------------------

class DeductionResp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.payment.deduction.v1.DeductionResp) */ {
 public:
  DeductionResp();
  virtual ~DeductionResp();

  DeductionResp(const DeductionResp& from);
  DeductionResp(DeductionResp&& from) noexcept
    : DeductionResp() {
    *this = ::std::move(from);
  }

  inline DeductionResp& operator=(const DeductionResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeductionResp& operator=(DeductionResp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DeductionResp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeductionResp* internal_default_instance() {
    return reinterpret_cast<const DeductionResp*>(
               &_DeductionResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DeductionResp& a, DeductionResp& b) {
    a.Swap(&b);
  }
  inline void Swap(DeductionResp* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeductionResp* New() const final {
    return CreateMaybeMessage<DeductionResp>(nullptr);
  }

  DeductionResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeductionResp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DeductionResp& from);
  void MergeFrom(const DeductionResp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeductionResp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.payment.deduction.v1.DeductionResp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_deduction_2eproto);
    return ::descriptor_table_deduction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kMessageFieldNumber = 3,
    kSuccessFieldNumber = 1,
    kCodeFieldNumber = 4,
  };
  // repeated .protocol.payment.deduction.v1.DeductionStruct data = 2;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::protocol::payment::deduction::v1::DeductionStruct* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::payment::deduction::v1::DeductionStruct >*
      mutable_data();
  private:
  const ::protocol::payment::deduction::v1::DeductionStruct& _internal_data(int index) const;
  ::protocol::payment::deduction::v1::DeductionStruct* _internal_add_data();
  public:
  const ::protocol::payment::deduction::v1::DeductionStruct& data(int index) const;
  ::protocol::payment::deduction::v1::DeductionStruct* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::payment::deduction::v1::DeductionStruct >&
      data() const;

  // string message = 3;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // uint32 code = 4;
  void clear_code();
  ::PROTOBUF_NAMESPACE_ID::uint32 code() const;
  void set_code(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_code() const;
  void _internal_set_code(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.payment.deduction.v1.DeductionResp)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::payment::deduction::v1::DeductionStruct > data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool success_;
  ::PROTOBUF_NAMESPACE_ID::uint32 code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_deduction_2eproto;
};
// -------------------------------------------------------------------

class DeductionReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protocol.payment.deduction.v1.DeductionReq) */ {
 public:
  DeductionReq();
  virtual ~DeductionReq();

  DeductionReq(const DeductionReq& from);
  DeductionReq(DeductionReq&& from) noexcept
    : DeductionReq() {
    *this = ::std::move(from);
  }

  inline DeductionReq& operator=(const DeductionReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeductionReq& operator=(DeductionReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DeductionReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeductionReq* internal_default_instance() {
    return reinterpret_cast<const DeductionReq*>(
               &_DeductionReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DeductionReq& a, DeductionReq& b) {
    a.Swap(&b);
  }
  inline void Swap(DeductionReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeductionReq* New() const final {
    return CreateMaybeMessage<DeductionReq>(nullptr);
  }

  DeductionReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeductionReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DeductionReq& from);
  void MergeFrom(const DeductionReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeductionReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protocol.payment.deduction.v1.DeductionReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_deduction_2eproto);
    return ::descriptor_table_deduction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTitleFieldNumber = 1,
    kDescFieldNumber = 2,
    kPayMethodIdFieldNumber = 3,
    kIdFieldNumber = 4,
  };
  // string title = 1;
  void clear_title();
  const std::string& title() const;
  void set_title(const std::string& value);
  void set_title(std::string&& value);
  void set_title(const char* value);
  void set_title(const char* value, size_t size);
  std::string* mutable_title();
  std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string desc = 2;
  void clear_desc();
  const std::string& desc() const;
  void set_desc(const std::string& value);
  void set_desc(std::string&& value);
  void set_desc(const char* value);
  void set_desc(const char* value, size_t size);
  std::string* mutable_desc();
  std::string* release_desc();
  void set_allocated_desc(std::string* desc);
  private:
  const std::string& _internal_desc() const;
  void _internal_set_desc(const std::string& value);
  std::string* _internal_mutable_desc();
  public:

  // uint32 pay_method_id = 3;
  void clear_pay_method_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 pay_method_id() const;
  void set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_pay_method_id() const;
  void _internal_set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 id = 4;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:protocol.payment.deduction.v1.DeductionReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr desc_;
  ::PROTOBUF_NAMESPACE_ID::uint32 pay_method_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_deduction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DeductionStruct

// string title = 1;
inline void DeductionStruct::clear_title() {
  title_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& DeductionStruct::title() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionStruct.title)
  return _internal_title();
}
inline void DeductionStruct::set_title(const std::string& value) {
  _internal_set_title(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionStruct.title)
}
inline std::string* DeductionStruct::mutable_title() {
  // @@protoc_insertion_point(field_mutable:protocol.payment.deduction.v1.DeductionStruct.title)
  return _internal_mutable_title();
}
inline const std::string& DeductionStruct::_internal_title() const {
  return title_.GetNoArena();
}
inline void DeductionStruct::_internal_set_title(const std::string& value) {
  
  title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DeductionStruct::set_title(std::string&& value) {
  
  title_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.payment.deduction.v1.DeductionStruct.title)
}
inline void DeductionStruct::set_title(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.payment.deduction.v1.DeductionStruct.title)
}
inline void DeductionStruct::set_title(const char* value, size_t size) {
  
  title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.payment.deduction.v1.DeductionStruct.title)
}
inline std::string* DeductionStruct::_internal_mutable_title() {
  
  return title_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DeductionStruct::release_title() {
  // @@protoc_insertion_point(field_release:protocol.payment.deduction.v1.DeductionStruct.title)
  
  return title_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DeductionStruct::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  title_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), title);
  // @@protoc_insertion_point(field_set_allocated:protocol.payment.deduction.v1.DeductionStruct.title)
}

// string desc = 2;
inline void DeductionStruct::clear_desc() {
  desc_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& DeductionStruct::desc() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionStruct.desc)
  return _internal_desc();
}
inline void DeductionStruct::set_desc(const std::string& value) {
  _internal_set_desc(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionStruct.desc)
}
inline std::string* DeductionStruct::mutable_desc() {
  // @@protoc_insertion_point(field_mutable:protocol.payment.deduction.v1.DeductionStruct.desc)
  return _internal_mutable_desc();
}
inline const std::string& DeductionStruct::_internal_desc() const {
  return desc_.GetNoArena();
}
inline void DeductionStruct::_internal_set_desc(const std::string& value) {
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DeductionStruct::set_desc(std::string&& value) {
  
  desc_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.payment.deduction.v1.DeductionStruct.desc)
}
inline void DeductionStruct::set_desc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.payment.deduction.v1.DeductionStruct.desc)
}
inline void DeductionStruct::set_desc(const char* value, size_t size) {
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.payment.deduction.v1.DeductionStruct.desc)
}
inline std::string* DeductionStruct::_internal_mutable_desc() {
  
  return desc_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DeductionStruct::release_desc() {
  // @@protoc_insertion_point(field_release:protocol.payment.deduction.v1.DeductionStruct.desc)
  
  return desc_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DeductionStruct::set_allocated_desc(std::string* desc) {
  if (desc != nullptr) {
    
  } else {
    
  }
  desc_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:protocol.payment.deduction.v1.DeductionStruct.desc)
}

// uint32 status = 3;
inline void DeductionStruct::clear_status() {
  status_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionStruct::_internal_status() const {
  return status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionStruct::status() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionStruct.status)
  return _internal_status();
}
inline void DeductionStruct::_internal_set_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  status_ = value;
}
inline void DeductionStruct::set_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionStruct.status)
}

// uint32 id = 4;
inline void DeductionStruct::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionStruct::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionStruct::id() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionStruct.id)
  return _internal_id();
}
inline void DeductionStruct::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void DeductionStruct::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionStruct.id)
}

// uint32 pay_method_id = 5;
inline void DeductionStruct::clear_pay_method_id() {
  pay_method_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionStruct::_internal_pay_method_id() const {
  return pay_method_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionStruct::pay_method_id() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionStruct.pay_method_id)
  return _internal_pay_method_id();
}
inline void DeductionStruct::_internal_set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  pay_method_id_ = value;
}
inline void DeductionStruct::set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_pay_method_id(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionStruct.pay_method_id)
}

// -------------------------------------------------------------------

// DeductionResp

// bool success = 1;
inline void DeductionResp::clear_success() {
  success_ = false;
}
inline bool DeductionResp::_internal_success() const {
  return success_;
}
inline bool DeductionResp::success() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionResp.success)
  return _internal_success();
}
inline void DeductionResp::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void DeductionResp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionResp.success)
}

// repeated .protocol.payment.deduction.v1.DeductionStruct data = 2;
inline int DeductionResp::_internal_data_size() const {
  return data_.size();
}
inline int DeductionResp::data_size() const {
  return _internal_data_size();
}
inline void DeductionResp::clear_data() {
  data_.Clear();
}
inline ::protocol::payment::deduction::v1::DeductionStruct* DeductionResp::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.payment.deduction.v1.DeductionResp.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::payment::deduction::v1::DeductionStruct >*
DeductionResp::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:protocol.payment.deduction.v1.DeductionResp.data)
  return &data_;
}
inline const ::protocol::payment::deduction::v1::DeductionStruct& DeductionResp::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::protocol::payment::deduction::v1::DeductionStruct& DeductionResp::data(int index) const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionResp.data)
  return _internal_data(index);
}
inline ::protocol::payment::deduction::v1::DeductionStruct* DeductionResp::_internal_add_data() {
  return data_.Add();
}
inline ::protocol::payment::deduction::v1::DeductionStruct* DeductionResp::add_data() {
  // @@protoc_insertion_point(field_add:protocol.payment.deduction.v1.DeductionResp.data)
  return _internal_add_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protocol::payment::deduction::v1::DeductionStruct >&
DeductionResp::data() const {
  // @@protoc_insertion_point(field_list:protocol.payment.deduction.v1.DeductionResp.data)
  return data_;
}

// string message = 3;
inline void DeductionResp::clear_message() {
  message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& DeductionResp::message() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionResp.message)
  return _internal_message();
}
inline void DeductionResp::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionResp.message)
}
inline std::string* DeductionResp::mutable_message() {
  // @@protoc_insertion_point(field_mutable:protocol.payment.deduction.v1.DeductionResp.message)
  return _internal_mutable_message();
}
inline const std::string& DeductionResp::_internal_message() const {
  return message_.GetNoArena();
}
inline void DeductionResp::_internal_set_message(const std::string& value) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DeductionResp::set_message(std::string&& value) {
  
  message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.payment.deduction.v1.DeductionResp.message)
}
inline void DeductionResp::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.payment.deduction.v1.DeductionResp.message)
}
inline void DeductionResp::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.payment.deduction.v1.DeductionResp.message)
}
inline std::string* DeductionResp::_internal_mutable_message() {
  
  return message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DeductionResp::release_message() {
  // @@protoc_insertion_point(field_release:protocol.payment.deduction.v1.DeductionResp.message)
  
  return message_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DeductionResp::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:protocol.payment.deduction.v1.DeductionResp.message)
}

// uint32 code = 4;
inline void DeductionResp::clear_code() {
  code_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionResp::_internal_code() const {
  return code_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionResp::code() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionResp.code)
  return _internal_code();
}
inline void DeductionResp::_internal_set_code(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  code_ = value;
}
inline void DeductionResp::set_code(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionResp.code)
}

// -------------------------------------------------------------------

// DeductionReq

// string title = 1;
inline void DeductionReq::clear_title() {
  title_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& DeductionReq::title() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionReq.title)
  return _internal_title();
}
inline void DeductionReq::set_title(const std::string& value) {
  _internal_set_title(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionReq.title)
}
inline std::string* DeductionReq::mutable_title() {
  // @@protoc_insertion_point(field_mutable:protocol.payment.deduction.v1.DeductionReq.title)
  return _internal_mutable_title();
}
inline const std::string& DeductionReq::_internal_title() const {
  return title_.GetNoArena();
}
inline void DeductionReq::_internal_set_title(const std::string& value) {
  
  title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DeductionReq::set_title(std::string&& value) {
  
  title_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.payment.deduction.v1.DeductionReq.title)
}
inline void DeductionReq::set_title(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.payment.deduction.v1.DeductionReq.title)
}
inline void DeductionReq::set_title(const char* value, size_t size) {
  
  title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.payment.deduction.v1.DeductionReq.title)
}
inline std::string* DeductionReq::_internal_mutable_title() {
  
  return title_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DeductionReq::release_title() {
  // @@protoc_insertion_point(field_release:protocol.payment.deduction.v1.DeductionReq.title)
  
  return title_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DeductionReq::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  title_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), title);
  // @@protoc_insertion_point(field_set_allocated:protocol.payment.deduction.v1.DeductionReq.title)
}

// string desc = 2;
inline void DeductionReq::clear_desc() {
  desc_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& DeductionReq::desc() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionReq.desc)
  return _internal_desc();
}
inline void DeductionReq::set_desc(const std::string& value) {
  _internal_set_desc(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionReq.desc)
}
inline std::string* DeductionReq::mutable_desc() {
  // @@protoc_insertion_point(field_mutable:protocol.payment.deduction.v1.DeductionReq.desc)
  return _internal_mutable_desc();
}
inline const std::string& DeductionReq::_internal_desc() const {
  return desc_.GetNoArena();
}
inline void DeductionReq::_internal_set_desc(const std::string& value) {
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void DeductionReq::set_desc(std::string&& value) {
  
  desc_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.payment.deduction.v1.DeductionReq.desc)
}
inline void DeductionReq::set_desc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.payment.deduction.v1.DeductionReq.desc)
}
inline void DeductionReq::set_desc(const char* value, size_t size) {
  
  desc_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.payment.deduction.v1.DeductionReq.desc)
}
inline std::string* DeductionReq::_internal_mutable_desc() {
  
  return desc_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* DeductionReq::release_desc() {
  // @@protoc_insertion_point(field_release:protocol.payment.deduction.v1.DeductionReq.desc)
  
  return desc_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void DeductionReq::set_allocated_desc(std::string* desc) {
  if (desc != nullptr) {
    
  } else {
    
  }
  desc_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:protocol.payment.deduction.v1.DeductionReq.desc)
}

// uint32 pay_method_id = 3;
inline void DeductionReq::clear_pay_method_id() {
  pay_method_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionReq::_internal_pay_method_id() const {
  return pay_method_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionReq::pay_method_id() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionReq.pay_method_id)
  return _internal_pay_method_id();
}
inline void DeductionReq::_internal_set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  pay_method_id_ = value;
}
inline void DeductionReq::set_pay_method_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_pay_method_id(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionReq.pay_method_id)
}

// uint32 id = 4;
inline void DeductionReq::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionReq::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DeductionReq::id() const {
  // @@protoc_insertion_point(field_get:protocol.payment.deduction.v1.DeductionReq.id)
  return _internal_id();
}
inline void DeductionReq::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void DeductionReq::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protocol.payment.deduction.v1.DeductionReq.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace deduction
}  // namespace payment
}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_deduction_2eproto
