// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fee.proto

#include "fee.pb.h"
#include "fee.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace protocol {
namespace fee {
namespace v1 {

static const char* FeeAdminApi_method_names[] = {
  "/protocol.fee.v1.FeeAdminApi/Logout",
  "/protocol.fee.v1.FeeAdminApi/AdminOp",
};

std::unique_ptr< FeeAdminApi::Stub> FeeAdminApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FeeAdminApi::Stub> stub(new FeeAdminApi::Stub(channel));
  return stub;
}

FeeAdminApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Logout_(FeeAdminApi_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AdminOp_(FeeAdminApi_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FeeAdminApi::Stub::Logout(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq& request, ::protocol::fee::v1::FeeAdminResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Logout_, context, request, response);
}

void FeeAdminApi::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq* request, ::protocol::fee::v1::FeeAdminResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void FeeAdminApi::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::fee::v1::FeeAdminResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void FeeAdminApi::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq* request, ::protocol::fee::v1::FeeAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

void FeeAdminApi::Stub::experimental_async::Logout(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::fee::v1::FeeAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::fee::v1::FeeAdminResp>* FeeAdminApi::Stub::AsyncLogoutRaw(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::fee::v1::FeeAdminResp>::Create(channel_.get(), cq, rpcmethod_Logout_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::fee::v1::FeeAdminResp>* FeeAdminApi::Stub::PrepareAsyncLogoutRaw(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::fee::v1::FeeAdminResp>::Create(channel_.get(), cq, rpcmethod_Logout_, context, request, false);
}

::grpc::Status FeeAdminApi::Stub::AdminOp(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq& request, ::protocol::fee::v1::FeeAdminResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_AdminOp_, context, request, response);
}

void FeeAdminApi::Stub::experimental_async::AdminOp(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq* request, ::protocol::fee::v1::FeeAdminResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_AdminOp_, context, request, response, std::move(f));
}

void FeeAdminApi::Stub::experimental_async::AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::fee::v1::FeeAdminResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_AdminOp_, context, request, response, std::move(f));
}

void FeeAdminApi::Stub::experimental_async::AdminOp(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq* request, ::protocol::fee::v1::FeeAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_AdminOp_, context, request, response, reactor);
}

void FeeAdminApi::Stub::experimental_async::AdminOp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::protocol::fee::v1::FeeAdminResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_AdminOp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protocol::fee::v1::FeeAdminResp>* FeeAdminApi::Stub::AsyncAdminOpRaw(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::fee::v1::FeeAdminResp>::Create(channel_.get(), cq, rpcmethod_AdminOp_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::protocol::fee::v1::FeeAdminResp>* FeeAdminApi::Stub::PrepareAsyncAdminOpRaw(::grpc::ClientContext* context, const ::protocol::fee::v1::FeeAdminReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::protocol::fee::v1::FeeAdminResp>::Create(channel_.get(), cq, rpcmethod_AdminOp_, context, request, false);
}

FeeAdminApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FeeAdminApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FeeAdminApi::Service, ::protocol::fee::v1::FeeAdminReq, ::protocol::fee::v1::FeeAdminResp>(
          [](FeeAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::fee::v1::FeeAdminReq* req,
             ::protocol::fee::v1::FeeAdminResp* resp) {
               return service->Logout(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FeeAdminApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FeeAdminApi::Service, ::protocol::fee::v1::FeeAdminReq, ::protocol::fee::v1::FeeAdminResp>(
          [](FeeAdminApi::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::protocol::fee::v1::FeeAdminReq* req,
             ::protocol::fee::v1::FeeAdminResp* resp) {
               return service->AdminOp(ctx, req, resp);
             }, this)));
}

FeeAdminApi::Service::~Service() {
}

::grpc::Status FeeAdminApi::Service::Logout(::grpc::ServerContext* context, const ::protocol::fee::v1::FeeAdminReq* request, ::protocol::fee::v1::FeeAdminResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FeeAdminApi::Service::AdminOp(::grpc::ServerContext* context, const ::protocol::fee::v1::FeeAdminReq* request, ::protocol::fee::v1::FeeAdminResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protocol
}  // namespace fee
}  // namespace v1

